---
title: "New pages"
date: 2021-02-13
---
title: "New pages"
author: "Safa Emre Özpolat"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  "Headings added, needs to be completed right now"
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
